[all]
server ansible_host=10.0.64.4 ansible_private_key_file="~/.ssh/devops_id_rsa" ansible_user="devops"
#server ansible_host=10.0.64.4 ansible_connection=ssh ansible_ssh_user=devops ansible_ssh_pass=Password
