# Gather IP facts from ipify.org and saved to variable ipify_public_ip
# This is not required if we use static IP.
- name: get my public IP
  ipify_facts:

- name: Create gitlab directories
  file: path={{ item }} recurse=yes state=directory
  with_items:
    - "{{ gitlab_config_dir }}"
    - "{{ gitlab_logs_dir }}"
    - "{{ gitlab_data_dir }}"

- name: Install Gitlab container
  docker_container:
    #hostname: "{{ gitlab_site }}"
    name: gitlab-container
    image: "{{ gitlab_image }}"
    ports:
      - "{{ gitlab_ssh_port }}:22"
      - "{{ gitlab_http_port }}:80"
      #- "{{ gitlab_https_port }}:443"
    volumes:
      - "{{ gitlab_config_dir }}:/etc/gitlab"
      - "{{ gitlab_logs_dir }}:/var/log/gitlab"
      - "{{ gitlab_data_dir }}:/var/opt/gitlab"
    state: started
    recreate: no

- name: deploy gitlab configuration
  template: src=gitlab.rb.j2 dest="{{ gitlab_config_dir }}/gitlab.rb" owner=root group=root mode=0644

- name: Copy systemd service script to start and stop the  gitlab-container
  copy: src=files/docker-gitlab.service dest=/etc/systemd/system

- name: Reload systemctl
  shell: systemctl reload-or-restart docker-gitlab

- name: Enable the docker-gitlab service
  shell: systemctl enable docker-gitlab
