- name: Add Docker Group
  group: name=docker state=present

- name: Add Docker Signing Key
  apt_key:
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
    filename: 'docker.list'

- name: Install Docker
  apt: name=docker-engine state=present

- name: Copy daemon.json . This is not needed if we use https for docker registry
  copy: src=files/daemon.json dest=/etc/docker/daemon.json

- name: restart docker after above step
  service:
    name: docker
    state: restarted

- name: Install necessary packages 
  apt: name={{ item }} state=present
    #become: true
  with_items:
    - python-pip


- name: Install docker-py
  pip: name=docker-py version=1.9.0
